### ISSUE TITLE
无法连接到25575之外的端口

### ISSUE THREAD

**Issue by MRNOBODY-ZST** [FAS-Server/MultiRconAPI#2]
看了一下源码
貌似config.json里的port是个假参数？
rcon_connection.py的main部分
```
if __name__ == '__main__':
	rcon = RconConnection('localhost', 25575, 'password')
	print('Login success? ', rcon.connect())
	while True:
		print('Server ->', rcon.send_command(input('Server <- ')))
```
端口写死了

**Comment by YehowahLiu** [comment]
这里是测试用的部分，确实是写死的

**Comment by 401U** [comment]
这是mcdr相关的测试逻辑，在真实应用时无问题

**Comment by MRNOBODY-ZST** [comment]
hmmm我在使用时的确无法连接到25585为端口的RCON
使用Rcon工具可以

**Comment by 401U** [comment]
`rcon_connection.py`为mcdr实现的rcon逻辑，如果要使用它来测试其他rcon端口的连接，只能修改mcdr的测试代码
本插件内另有一个`RconTest.py`，能够满足任意端口的rcon连接测试
注意，**以上都是供开发者测试rcon连接的，本插件目标使用场景还是作为mcdr插件使用**
如仍有疑问，请提供更多信息
