### ISSUE TITLE
远程连接到MCDR服务端

### ISSUE THREAD

**Issue by MRNOBODY-ZST** [FAS-Server/MultiRconAPI#3]
想问一下有没有方法能够远程连接到MCDR服务器
使用Rcon方法的话只能执行MC内部指令 无法执行MCDR专属指令（例如”!!qb list“）
或者麻烦Fallen写一个Rcon出来？（狗头保命

**Comment by 401U** [comment]
[ChatBridge](https://github.com/TISUnion/chatbridge)和[ChatBridgeReforged](https://github.com/R1ckyH/ChatBridgeReforged) 应该满足，但是前者支持的指令有限，可能需要自行拓展；后者需要自行编写插件
